language: python

git:
    quiet: true

services:
    - docker

stages:
    - build

before_install:
    - pip install --upgrade pip setuptools

jobs:
    include:
        - stage: build
          script:
            - make docker-image
            - docker tag raymondnumbergenerator/portra:latest raymondnumbergenerator/portra:current
            - make docker-run
            - docker inspect portra
            - if [[ $( docker inspect -f {{.State.Running}} portra ) != "true" ]] ; then exit 1; fi

